### ISSUE TITLE
Citations in perplexity / Add newline character in case one is missing

### ISSUE THREAD

**Issue by silgon** [kardolus/chatgpt-cli#113]
Hi again!
I just started using the Perplexity API with this package. I do not get the citations, do you have any insights on what I might be doing wrong? My configuration is almost as in the readme, just with the model changed.

```yaml
name: perplexity
api_key: ""
model: sonar
max_tokens: 4096
context_window: 8192
role: Be precise and concise.
temperature: 1
top_p: 1
frequency_penalty: 0
presence_penalty: 0
thread: test
omit_history: false
url: https://api.perplexity.ai
completions_path: /chat/completions
models_path: /models
auth_header: Authorization
auth_token_prefix: 'Bearer '
command_prompt: '[%datetime] [Q%counter] [%usage]'
auto_create_new_thread: true
track_token_usage: true
debug: false
```
