### ISSUE TITLE
Update Readme on Chatgpt vs OpenAI API models?



### ISSUE THREAD

**Issue by cameronelliott** [kardolus/chatgpt-cli#12]
This is a great project!

But, in my quest for looking for a way to use the same model that "chat.openapi.com" uses also from the CLI as the browser, I guess I need to keep looking.

I mean of course it's really Openapi's decisions not to offer the ChatGPT model via an API yet.

I think it would benefit this project, if it went to a little bit of effort to explain that in the Readme.

The fact that you can access many different OpenAI models via their APIs, but the ChatGPT model is not yet available.

It would also be worth mentioning the pricing difference.

**Comment by kardolus** [comment]
Hello @cameronelliott,

Thank you for your feedback and for bringing attention to the model availability and pricing differences between the web-based platform and the API endpoint. 

I will update the README accordingly. 

OpenAI indeed has a pattern of debuting new features and models on their web platform (chat.openai.com) before extending them to the API (api.openai.com). I find the $20 monthly subscription worthwhile for gaining early access to new features like file upload and plugin utilization, despite the cost-effectiveness of API calls via the CLI. The staggered release strategy does provide an incentive to maintain the monthly subscription.

I am on Microsoft's waiting list for their version of ChatGPT. It's fascinating to see established companies like Stripe and Shopify leveraging it already. I've configured the API endpoint and paths to be adjustable, allowing for the potential switch to a different vendor, as illustrated below:

```yaml
name: openai
model: gpt-4-0613
max_tokens: 8192
role: You are a helpful assistant.
thread: default
omit_history: false
url: https://api.openai.com
completions_path: /v1/chat/completions
models_path: /v1/models
```

I haven't received feedback yet though from folks using the CLI with Microsoft's version of ChatGPT, but I'm looking forward to any insights that might come from the community.

Looking forward to hearing more of your thoughts!
