### ISSUE TITLE
How to use with Azure?

### ISSUE THREAD

**Issue by AlaShibanAtKlo** [kardolus/chatgpt-cli#18]
Great work on the CLI! 
How do I configure it to use our azure openai deployment? Thanks!

**Comment by kardolus** [comment]
Hey @AlaShibanAtKlo! Super stoked you reached out. 😊 I've been crossing my fingers for someone with Azure access to pop up since I don't have direct access to Azure myself. I think this CLI should play nice with Azure. Mind giving these settings a try?

Put this into your `~/.chatgpt-cli/config.yaml`:

```yaml
name: azure
api_key: <your api key>
model: gpt-4
max_tokens: 2048
temperature: 1
top_p: 1
frequency_penalty: 0
presence_penalty: 0
url: https://<your-resource-name>.api.azure-openai.net
completions_path: /v1/models/gpt-4:generate
auth_header: Authorization
auth_token_prefix: 'Bearer '
```

Heads up, the `name` here (azure) is the prefix for any env vars you want to slot in (like `AZURE_API_KEY` for api_key).

If things go sideways, it would be amazing if you could provide the output of this cURL:

```bash
curl -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer <your api key>" \
-d '{"model": "gpt-4", "prompt": "Hello, how are you?", "max_tokens": 2048}' \
https://<your-resource-name>.api.azure-openai.net/v1/models/gpt-4:generate
```

I could use the output to tweak the CLI for Azure compatibility. Fingers crossed it just works, but if not, let's crack this together!
